set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports oled_clk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN G1 [get_ports oled_rst]
set_property PACKAGE_PIN J15 [get_ports rst_n]

set_property PACKAGE_PIN G3 [get_ports oled_clk]

set_property IOSTANDARD LVCMOS33 [get_ports oled_cs]
set_property PACKAGE_PIN H2 [get_ports oled_cs]
set_property IOSTANDARD LVCMOS33 [get_ports oled_data_out]
set_property PACKAGE_PIN H1 [get_ports oled_data_out]
set_property IOSTANDARD LVCMOS33 [get_ports oled_dc]
set_property PACKAGE_PIN H4 [get_ports oled_dc]
set_property IOSTANDARD LVCMOS33 [get_ports oled_run_flag]
set_property PACKAGE_PIN H17 [get_ports oled_run_flag]

set_property IOSTANDARD LVCMOS33 [get_ports bl_rx]
set_property PACKAGE_PIN J2 [get_ports bl_rx]
set_property IOSTANDARD LVCMOS33 [get_ports bl_tx]
set_property PACKAGE_PIN F6 [get_ports bl_tx]
set_property IOSTANDARD LVCMOS33 [get_ports bluetooth_en]
set_property PACKAGE_PIN G6 [get_ports bluetooth_en]

set_property IOSTANDARD LVCMOS33 [get_ports en0]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display7[6]}]
set_property PACKAGE_PIN T10 [get_ports {display7[6]}]
set_property PACKAGE_PIN R10 [get_ports {display7[5]}]
set_property PACKAGE_PIN K16 [get_ports {display7[4]}]
set_property PACKAGE_PIN K13 [get_ports {display7[3]}]
set_property PACKAGE_PIN P15 [get_ports {display7[2]}]
set_property PACKAGE_PIN T11 [get_ports {display7[1]}]
set_property PACKAGE_PIN L18 [get_ports {display7[0]}]
set_property PACKAGE_PIN J17 [get_ports en0]
set_property IOSTANDARD LVCMOS33 [get_ports display7_dp]
set_property PACKAGE_PIN H15 [get_ports display7_dp]
set_property IOSTANDARD LVCMOS33 [get_ports en1]
set_property PACKAGE_PIN J18 [get_ports en1]


set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sleep_pos[0]}]
set_property PACKAGE_PIN U13 [get_ports {sleep_pos[5]}]
set_property PACKAGE_PIN K2 [get_ports {sleep_pos[4]}]
set_property PACKAGE_PIN T14 [get_ports {sleep_pos[3]}]
set_property PACKAGE_PIN P14 [get_ports {sleep_pos[2]}]
set_property PACKAGE_PIN J14 [get_ports {sleep_pos[1]}]
set_property PACKAGE_PIN T9 [get_ports {sleep_pos[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports over]
set_property PACKAGE_PIN V11 [get_ports over]
