# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/workspace/vivadoProjects/WaduES/WaduES.cache/wt [current_project]
set_property parent.project_path D:/workspace/vivadoProjects/WaduES/WaduES.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/es.vh
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/commands.vh
}
read_verilog -library xil_defaultlib {
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/cal_es.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/Display_7.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/display7_divider.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/Zoomer.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/Display_OLED.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/bluetooth_tx.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/bluetooth_rx.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/bluetooth_divider.v
  D:/workspace/vivadoProjects/WaduES/WaduES.srcs/sources_1/new/Control.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/workspace/vivadoProjects/WaduES/WaduES.srcs/constrs_1/new/control_xdc.xdc
set_property used_in_implementation false [get_files D:/workspace/vivadoProjects/WaduES/WaduES.srcs/constrs_1/new/control_xdc.xdc]


synth_design -top Control -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Control.dcp

catch { report_utilization -file Control_utilization_synth.rpt -pb Control_utilization_synth.pb }
