######################################################################
#
# File name : Control.udo
# Created on: Sat Dec 15 10:45:05 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
