######################################################################
#
# File name : oled_tb.udo
# Created on: Tue Dec 11 16:33:32 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
