######################################################################
#
# File name : oled_tb_wave.do
# Created on: Sat Dec 15 11:35:44 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
