######################################################################
#
# File name : oled_tb_compile.do
# Created on: Sat Dec 15 11:35:40 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../WaduES.srcs/sources_1/new/Display_OLED.v" \
"../../../WaduES.srcs/sources_1/new/Control.v" \
"../../../WaduES.srcs/sim_1/new/oled_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

