######################################################################
#
# File name : oled_tb_simulate.do
# Created on: Sat Dec 15 11:35:44 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.oled_tb xil_defaultlib.glbl

do {oled_tb_wave.do}

view wave
view structure
view signals

do {oled_tb.udo}

run 1000ns
